apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: testsecret
    namespace: default
data:
    testkey: ENC[AES256_GCM,data:1nRuG6WwsYI=,iv:DZQ8EI1wNzZgzDtwoIankgtoNrzhImzE2kKKYmoimiE=,tag:sNIudrT9V9OVU/YL6XJwFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOStkRmRkaWhIankzekM0
            L3hQSlZxSXl5bks5WUVyYlFZSEpDcUxvZlRVCkViNG14VUVhcDZodVg2MTRvU2tH
            WUx5SVpNdlJlZGFJMnNjY05KaTdyeFkKLS0tIDE3ZUFlYU1lWUtCMGV0WFUzS0t5
            TG9leFpxY2lwaVlNNGZobGJkcFVHZ2sKh6FWTaKaAX61gfoZFSRHpPFtZPubEhsT
            Z5W7PBW32Ng998UpXRHGBnLOM32ln3TDIecK6FaSJ5Mh3UzXmp17NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gkxdegjfkl3krek9nrcc5hdxdaxa8x9jdxhrtujq7lp2f8uqus4q72tc2w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T12:28:45Z"
    mac: ENC[AES256_GCM,data:I9gSn6/06hPF+jcoZ6tiKwuWd8Jy2bwkH0vMi1PTHTIrHt85JrzITbJGqdNZxn4nZm0lZhnByfHAm4LatVKekvhBrg2Ba7Olztotvr9nG2pjpS/6VeBWoyRFlI1J5oJxL+T5z3NVG8hdoxlBxOhm6okTSYkmU4ScgdgZDjzAsos=,iv:iolN9TXr55aLqzPwJ1/zX67akIJ3nI4SDO5oNCsz2B0=,tag:tWfST8mHacAzfeB3GM+jNw==,type:str]
    version: 3.13.2
